name: Build and publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python and uv
        uses: ./.github/actions/uv

      - name: Build and Publish
        run: |
          uv build --wheel
          uv publish -p ${{ secrets.PYPI_TOKEN }} -u __token__
        shell: bash
